version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://vutrinh:123456@db:5432/project_development
    command: ["./entrypoint.sh"]

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vutrinh
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: project_development