development:
  secret_key_base: Ryuefr0cRwwZ5N0wIMYXMSmN4QebXgeW
  youtube_key: AIzaSyCC-mi1bwCk__Ir5GRPbqgYKeUg-FnEH-s

test:
  secret_key_base: Ryuefr0cRwwZ5N0wIMYXMSmN4QebXgeW

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>